### ISSUE TITLE
Add arguments to clean project data directory

### ISSUE THREAD

**Issue by emthompson-usgs** [usgs/groundmotion-processing#596] opened 2021-01-11 20:09 UTC
I'm not exactly sure what the best behavior here is. Could be to delete all raw data and leave workspace files.

**Comment by jas82** [comment] 2021-02-05 23:06
Is this issue not a duplicate of https://github.com/usgs/groundmotion-processing/issues/378?

**Comment by emthompson-usgs** [comment] 2021-02-06 00:05
The described behavior is slightly different in each, but these should probably be merged. I'll close the other and add a comment here to include what it describes.

**Comment by emthompson-usgs** [comment] 2021-02-06 00:06
Also include options to delete workspace, report, output plot and table files.

**Comment by jas82** [comment] 2021-02-06 00:51
So maybe something like this:

```gmrecords clean all``` (or just clean)
```gmrecords clean workspace```
```gmrecords clean plots raw```

**Closed** 2021-10-30 03:23 UTC
Labels: feature
