### ISSUE TITLE
Sort the IMT columns in the metrics tables outputted by gmprocess

### ISSUE THREAD

**Issue by jrekoske-usgs** [usgs/groundmotion-processing#338] opened 2019-07-08 19:02 UTC
It would be nice if the columns were sorted like PGA, PGV, SA(1.0), SA(2.0), SA(3.0). The order of the columns seems to come out random right now.

**Comment by emthompson-usgs** [comment] 2019-07-08 19:45
Agreed. This is basically a duplicate of #332... but I'll go close that one.

**Closed** 2019-07-15 17:05 UTC
